"""
refinement.py
-------------
Uses the new Gemini API (google-genai) to refine and polish translations 
generated by the NLLB model.
"""

import os
from dotenv import load_dotenv
from google import genai

# 1. Load the environment variables from the .env file
load_dotenv()

# 2. Get the API key
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    raise ValueError("⚠️ GEMINI_API_KEY environment variable not set. Please check your .env file.")

# 3. Initialize the new GenAI client
client = genai.Client(api_key=api_key)

# ============================================
# CORE REFINEMENT FUNCTION
# ============================================
def refine_translation(original_text: str, draft_translation: str, target_language: str, domain: str) -> str:
    """
    Refines a draft translation using Gemini to fit a specific domain.
    """
    prompt = f"""
You are an expert bilingual translator and a technical localization specialist in the following domain: {domain}.

I have a source text and a draft translation in {target_language}.
Your task is to refine the draft translation so that it uses the correct terminology, tone, and natural phrasing expected by professionals in the {domain} domain. 

Source Text:
"{original_text}"

Draft Translation ({target_language}):
"{draft_translation}"

Provide ONLY the refined {target_language} translation. Do not include any explanations, quotes, introductory text, or markdown blocks. Just the final text.
"""
    
    try:
        # Use the new SDK syntax to generate content (using the latest flash model)
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        
        refined_text = response.text.strip()
        
        if not refined_text:
            return draft_translation
            
        return refined_text

    except Exception as e:
        print(f"⚠️ Gemini Refinement Error: {e}")
        return draft_translation

# ============================================
# EXAMPLE USAGE
# ============================================
if __name__ == "__main__":
    test_source = "The server experienced a segfault due to a null pointer dereference."
    test_draft = "सर्वर ने एक शून्य सूचक संदर्भ के कारण एक सेगफॉल्ट का अनुभव किया।" 
    
    target_lang = "Hindi"
    domain_context = "Computer Science and Software Engineering"

    print("=" * 50)
    print("TRANSLATION REFINEMENT DEMO")
    print("=" * 50)
    print(f"Original Source : {test_source}")
    print(f"NLLB Draft      : {test_draft}")
    print("-" * 50)
    
    print(f"🔄 Polishing via Gemini for the '{domain_context}' domain...")
    
    refined = refine_translation(
        original_text=test_source,
        draft_translation=test_draft,
        target_language=target_lang,
        domain=domain_context
    )
    
    print(f"✅ Refined Output: {refined}")